### ISSUE TITLE
bullet_reasoning launch dependecies

### ISSUE THREAD

**Issue by bbrieber** [cram2/cram_3d_world#2]
the package bullet_reasoning_utilities depends on pr2_description_lowres...
and the package bullet_reasoning_interface depends on spatial_relations_demo...

I guess they should only exec_depend on those packages...

**Comment by gaya-** [comment]
Fixed in e6f65f033840a216563a90cf5869fea5ca09605c and 8ec899e0bdfebd3e169c249e42d1aefebfdabb40.
