### ISSUE TITLE
robot state is not updated correctly from tf

### ISSUE THREAD

**Issue by marcniehaus** [cram2/cram_3d_world#3]
If cram_bullet_reasoning is used in combination with a simulated PR2 in gazebo, the robot state in the bullet world is supposed to be equal to the robot state in gazebo. However, as soon as the state is updated the torso of the robot falls through the ground (See attached screenshot).
![screenshot](https://cloud.githubusercontent.com/assets/12801015/12511474/d715ffcc-c111-11e5-897d-2da366cf9a0e.png)

**Comment by gaya-** [comment]
@marcniehaus Thanks for the bug report.
This should have been fixed with f2297323ee73f1940079bf69a0bc2d102de2466d.
Please let me know if that helps.
There might be similar bugs all over the place, I'll check this as soon as possible.

**Comment by gaya-** [comment]
Found another similar bug in ``cram_pr2``, should have been fixed with https://github.com/cram2/cram_pr2/commit/77eebbfe24092bae10239d01f8c55ceb42812c6f.
That should be all, I guess.
