### ISSUE TITLE
No tf transform between fl_caster_rotation_link and base_footprint?

### ISSUE THREAD

**Issue by fairlight1337** [cram2/cram_3d_world#7]
I'm using `cram_3d_world` in [longterm_fetch_and_place](https://github.com/code-iai/longterm_fetch_and_place). I can successfully initialize the 3d world (aka bullet window), populate it with a kitchen model, the ground plane, and a PR2 model. Location resolution also works and they are published to the debug window just fine.

After doing a navigation action just now (working in Gazebo, the robot actually moves, `tf` is being published correctly, and the joint state publisher of the robot works well), I encountered this message:
```lisp
[(SET-ROBOT-STATE-FROM-TF) WARN] 235.608: Failed with transform-stamped-error: No transform was published between frames fl_caster_rotation_link and base_footprint
```
I did a `(roslisp-utils:startup-ros)` in the beginning and saw, apart from other lines, this output:
```lisp
[(ROSNODE) INFO] 60.226: ROS init #<FUNCTION CRAM-TF::INIT-TF>.
[(CRAM-TF INIT-TF) INFO] 60.226: Set *fixed-frame* to "map".
[(CRAM-TF INIT-TF) INFO] 60.336: Initialized *transformer* to a cl-tf:transform-listener.
[(CRAM-TF INIT-TF) INFO] 60.346: Set *tf-default-timeout* to 4.0.
[(CRAM-TF INIT-TF) INFO] 60.376: Set *ROBOT-BASE-FRAME* to "base_footprint".
```
Do I need to initialize something else when using 3d world or is there something missing when used with Gazebo? I use [this](https://github.com/code-iai/longterm_fetch_and_place/blob/master/ltfnp_executive/src/utils.lisp#L79) function to set it up.

Thanks.

**Comment by gaya-** [comment]
Could you try `rosrun tf tf_echo fl_caster_rotation_link base_footprint` and see if there are any transforms published at all?

**Comment by fairlight1337** [comment]
Oh, I just noticed a second one:
```lisp
[(SET-ROBOT-STATE-FROM-TF) WARN] 200.517: Failed with transform-stamped-error: No transform was published between frames base_footprint and map
```
So there might be something off with `tf` after all.

**Comment by fairlight1337** [comment]
Sure, this is what I get:
```bash
14:45:01 ~$ rosrun tf tf_echo fl_caster_rotation_link base_footprint
At time 710.689
- Translation: [0.225, -0.225, -0.079]
- Rotation: in Quaternion [0.000, 0.000, 0.707, 0.707]
            in RPY (radian) [0.000, -0.000, 1.571]
            in RPY (degree) [0.000, -0.000, 90.000]
```

**Comment by fairlight1337** [comment]
Ah, just ran it a second time and it first bailed out with an exception before returning to normal operation:
```bash
14:46:37 ~$ rosrun tf tf_echo fl_caster_rotation_link base_footprint
Failure at 778.073000000
Exception thrown:"fl_caster_rotation_link" passed to lookupTransform argument target_frame does not exist. 
The current list of frames is:

Failure at 778.073000000
Exception thrown:"fl_caster_rotation_link" passed to lookupTransform argument target_frame does not exist. 
The current list of frames is:

At time 779.049
- Translation: [0.225, -0.225, -0.079]
- Rotation: in Quaternion [0.000, 0.000, 0.707, 0.707]
            in RPY (radian) [0.000, -0.000, 1.571]
            in RPY (degree) [0.000, -0.000, 90.000]
At time 780.019
- Translation: [0.225, -0.225, -0.079]
- Rotation: in Quaternion [0.000, 0.000, 0.707, 0.707]
            in RPY (radian) [0.000, -0.000, 1.571]
            in RPY (degree) [0.000, -0.000, 90.000]
```

**Comment by fairlight1337** [comment]
@gaya- as discussed in person, I'll raise the `cram-tf::*tf-default-timeout*` to `10.0` for now; thanks. This works fine - Gazebo just seems to be slower than the actual robot.

Also, the second thing about the exception: This seems to just be `tf_echo` not filling up its buffer before running its first lookups. So nothing to worry about there.

I'll close this issue then.

**Comment by gaya-** [comment]
So, in order to not have this problem in the future, should we change the default tf timeout to 10 in `cram_tf`? We don't win much from having it 4.0 per default, but having it 10 helps to avoid some errors.
I'm talking about this line:
https://github.com/cram2/cram_plans/blob/master/cram_tf/src/setup.lisp#L76

**Comment by gaya-** [comment]
Forgot to say, 4.0 is the default timeout for simulation, when `use_sim_time` is true. When it's not true, the default is 2.0. I have set it to 4.0 on my very fast laptop, so on slower laptops it would definitely take longer, especially if the scenario is computationally intensive.

**Comment by fairlight1337** [comment]
Agree, if it helps, let's change the default value. I like the idea of putting it as an optional parameter in the designators as well (learning and whatnot). I'll put in the designator rule for the navigation process module. Can you maybe change the default setting to 10? Thanks!

**Comment by gaya-** [comment]
> Can you maybe change the default setting to 10?

Ok, I will make a PR tomorrow.

**Comment by fairlight1337** [comment]
Great, thanks. Opened the PR for the timeout here: https://github.com/cram2/cram_pr2/pull/6
